let input = require("fs").readFileSync("/dev/stdin","utf8");
let linhas = input.split("\n");
let linha = linhas.shift().split(" ");
let linha2 = linhas.shift().split(" ");
let x1 = parseFloat(linha[0]);
let y1 = parseFloat(linha[1]);
let x2 = parseFloat(linha2[0]);
let y2 = parseFloat(linha2[1]);
let distancia = Math.sqrt((x2-x1)*(x2-x1) + (y2-y1)*(y2-y1));
console.log(`${distancia.toFixed(4)}`);